apiVersion: v1
kind: Pod
metadata:
  name: my-python-app-pod
spec:
  containers:
    - name: my-python-app-container
      image: my-python-app:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "256Mi"
          cpu: "0.5"
        limits:
          memory: "512Mi"
          cpu: "1"
