# Generated by Django 3.2.25 on 2025-01-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(max_length=10)),
                ('topic', models.CharField(max_length=100)),
                ('signal', models.CharField(max_length=50)),
                ('local_time', models.DateTimeField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('SMA_5', models.FloatField()),
                ('EMA_10', models.FloatField()),
                ('delta', models.FloatField()),
                ('gain', models.FloatField()),
                ('loss', models.FloatField()),
                ('avg_gain_10', models.FloatField()),
                ('avg_loss_10', models.FloatField()),
                ('rs', models.FloatField()),
                ('RSI_10', models.FloatField()),
            ],
        ),
    ]
