
apiVersion: v1
kind: Service
metadata:
  name: django-service-db
  labels:
    app: django-with-db
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
  selector:
    app: django
