
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-with-db
  labels:
    app: django-with-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-with-db
  template:
    metadata:
      labels:
        app: django-with-db
    spec:
      containers:
      - name: django
        image: django-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "postgres-service"  # نام سرویس پایگاه داده
        - name: DB_NAME
          value: "django_db"
        - name: DB_USER
          value: "django_user"
        - name: DB_PASSWORD
          value: "securepassword"
